name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    # Declare all secret env vars once here
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Debug Jest setup
        run: |
          npx jest --version || echo "Jest not found"
          npm ls jest || echo "Jest not installed"

      - name: Run tests and generate JSON output
        run: npx jest --ci --json > test-results.json || echo "Tests failed, but continuing"
        # No need to redefine env here, inherited from job env

      - name: Create custom test log and export data
        if: always()
        run: |
          node -e "
            const fs = require('fs');
            let log = ['Test Summary - ' + new Date().toISOString()];
            let summary = { timestamp: new Date().toISOString(), tests: {} };
            try {
              const results = JSON.parse(fs.readFileSync('test-results.json', 'utf8'));
              log.push(
                'Total Tests: ' + (results.numTotalTests || 'N/A'),
                'Passed: ' + (results.numPassedTests || 'N/A'),
                'Failed: ' + (results.numFailedTests || 'N/A'),
                'Pending: ' + (results.numPendingTests || 'N/A')
              );
              summary.tests = {
                total: results.numTotalTests || 0,
                passed: results.numPassedTests || 0,
                failed: results.numFailedTests || 0,
                pending: results.numPendingTests || 0
              };
            } catch (e) {
              log.push('Error parsing test-results.json: ' + e.message);
              summary.error = e.message;
            }
            fs.writeFileSync('test-results-custom.log', log.join('\n'));
            fs.writeFileSync('test-summary.json', JSON.stringify(summary, null, 2));
          "

      - name: Debug AWS setup
        if: always()
        run: |
          aws --version
          aws s3 ls s3://${S3_BUCKET_NAME}/test-logs/ --region ap-southeast-2 || echo "Failed to list S3 test-logs"

      - name: Upload test log to S3
        if: always()
        run: |
          aws s3 cp test-results-custom.log s3://${S3_BUCKET_NAME}/test-logs/test-results-${{ github.sha }}.log --region ap-southeast-2 || echo "Failed to upload to S3"

      - name: Upload test log to Elastic Beanstalk logs
        if: always()
        run: |
          aws s3 cp test-results-custom.log s3://${S3_BUCKET_NAME}/DEV-API/DEVAPI-env/logs/test-results-${{ github.sha }}.log --region ap-southeast-2 || echo "Failed to upload to Elastic Beanstalk logs"

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results.json
            test-results-custom.log
            test-summary.json
